"""Initial Migration

Revision ID: 35d0ad109489
Revises: 
Create Date: 2026-03-08 23:10:09.605226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d0ad109489'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('cashback', sa.Float(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('refuels',
    sa.Column('id_request', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('bonus', sa.Float(), nullable=True),
    sa.Column('additional_percentage', sa.Float(), nullable=True),
    sa.Column('liters', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_request')
    )
    op.create_table('payments',
    sa.Column('id_payment', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_refuel', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_refuel'], ['refuels.id_request'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['total_value'], ['refuels.value'], ),
    sa.PrimaryKeyConstraint('id_payment')
    )
    op.create_table('promotions',
    sa.Column('id_promotion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fuel_type', sa.String(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fuel_type'], ['refuels.fuel_type'], ),
    sa.PrimaryKeyConstraint('id_promotion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promotions')
    op.drop_table('payments')
    op.drop_table('refuels')
    op.drop_table('users')
    # ### end Alembic commands ###
